version: 0.1.0
dotnet_csproj:
  patch: true
  file: '**\*.csproj'
  version: '{version}'
  package_version: '{version}'
  assembly_version: '{version}'
  file_version: '{version}'
  informational_version: '{version}'
test_script:
  -cmd: xunit.console 'vaultconfiguration.tests\bin\Debug\netcoreapp2.0\vaultconfiguration.tests.dll' /appveyor